version: '3.8'

services:
  backend:
    build: .
    container_name: dotecommerce-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dotecommerce-network

  mongo:
    image: mongo:6
    container_name: dotecommerce-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - dotecommerce-network

  redis:
    image: redis:7-alpine
    container_name: dotecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dotecommerce-network

volumes:
  mongo-data:
  redis-data:

networks:
  dotecommerce-network:
    driver: bridge
