// src/dto/cart.dto.ts
import { Document, Types } from 'mongoose';

// Interface for plain cart data (without Mongoose Document methods)
export interface ICartData {
  user: Types.ObjectId | string;
  items: {
    _id?: Types.ObjectId; // Optional for new items, auto-generated by Mongoose
    product: Types.ObjectId | string;
    variantName: string;
    variantValue: string;
    price: number;
    quantity: number;
    images: string[];
  }[];
  _id: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

// Interface for Mongoose document
export interface ICart extends Document<Types.ObjectId> {
  user: Types.ObjectId | string;
  items: {
    _id?: Types.ObjectId; // Optional for new items, auto-generated by Mongoose
    product: Types.ObjectId | string;
    variantName: string;
    variantValue: string;
    price: number;
    quantity: number;
    images: string[];
  }[];
  _id: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

export interface AddToCartDTO {
  product: string; // Product ObjectId
  variantName: string; // e.g., "Color"
  variantValue: string; // e.g., "Red"
  quantity: number;
  price: number;
  images: string[];
}

export interface UpdateCartItemDTO {
  product: string;
  variantName: string;
  variantValue: string;
  quantity: number;
}

export interface AddToCartRequestBody {
  product: string;
  variantName: string;
  variantValue: string;
  quantity: number;
  price: number;
  images: string[];
}

export interface UpdateCartItemRequestBody {
  product: string;
  variantName: string;
  variantValue: string;
  quantity: number;
}
