name: Deploy to Docker Hub and Render

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t yabnardi/dotecommersebackend:latest .
          docker push yabnardi/dotecommersebackend:latest

  redeploy-render:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Trigger redeploy on Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvufjvi4d50c73auk8i0?key=${{ secrets.RENDER_DEPLOY_HOOK }}"
